### ISSUE TITLE
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.github.cjwizard.i18n.cjwizard, locale de_CH (Version 1.0.5)

### ISSUE THREAD

**Issue by Petikoch** [cjwizard/cjwizard#38]
I just tried to integrate the released 1.0.5 Version...

At runtime, I get 

    Caused by: java.util.MissingResourceException: Can't find bundle for base name com.github.cjwizard.i18n.cjwizard, locale de_CH
    	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
    	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
    	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
    	at com.github.cjwizard.WizardContainer.<clinit>(WizardContainer.java:61)
    	... 43 common frames omitted

I looked into the `cjwizard-1.0.5.jar`, there is indeed the i18n package missing with the properties files...

Best regards,
Peti

**Comment by creswick** [comment]
ugh, that's embarrassing!

I've moved the properties files into 'resources', and they appear to be in the jar now.  version 1.0.6 is on jcenter.

Could you try that and close this if it's working?

I've also opened #39 so I don't forget to set up a sample project that will help test for this sort of failure in the future.

Thanks!

**Comment by Petikoch** [comment]
Thanks @creswick for fixing! Works with 1.0.6. 

I successfully switched from an "old" 0.2 Version to the new public 1.0.6 Version.

Thanks for creating and sharing CJWizard!

Best regards from Switzerland,
Peti

**Comment by creswick** [comment]
@Petikoch Thanks for the help & patience!
